### ISSUE TITLE
z-index with open modal/dialog when summernote is set to fullscreen

### ISSUE THREAD

**Issue by StudioJunkyard** [semplon/summernote-ext-elfinder#1]
I'm not sure if this is an issue with Summernote or elFinder.
I remember mention to you in Summernote Issue tracker about modals not opening twice, I worked out what that issue was, was my fault. I had a script listening to the bootstrap hidden, that was removing the modal that was open, hence removing the modals content. I originally though this may have been something to do with the elFinder not showing when Summernote is set to full screen. The other modals open as expected. I've looked through the css, of summernote, and elFinder to see if I can see the z-index higher to overcome elFinder now showing. I know it's a z-index issue, 'cos when switching Summernote back out of fullscreen elFinder is open, which means it was behind Summernote. Seeing as I couldn't find (mind it could be me, lol), I was wondering if Summernote might set the z-index programmatically. Anyway, would like to hear your thoughts.

**Comment by semplon** [comment]
hello @StudioJunkyard , sorry for late reply. I think we can modify the css of the elFinder. I've done it and test it, and it work well. See the demo below. I use your elfinder custom icon and add this code at the css.
```css
.dialogelfinder {
    z-index: 20000;
}
```

![summernote-elfinder](https://cloud.githubusercontent.com/assets/3163608/17648305/78423c44-6239-11e6-8416-f338aa2565ea.png)

see this video for more detail.
https://youtu.be/-dmoQFdjygY

**Comment by StudioJunkyard** [comment]
I'd actually forgotten about this, lol. Cheers.
